export type Theme = {
  bg: string;
  card: string;
  cardHead: string;
  border: string;
  primary: string;
  primaryHover: string;
  text: string;
  muted: string;
  dimmer: string;
  label: string;
  inputBg: string;
  lockedBg: string;
  lockedText: string;
  success: string;
  warn: string;
  error: string;
  successBg: string;
  successBorder: string;
  errorBg: string;
  errorBorder: string;
  withoutAccent: string;
  withAccent: string;
  barBg: string;
  latencyColor: string;
  tableRowBorder: string;
  toastBg: string;
  navBg: string;
  navBorder: string;
  navText: string;
  navActiveText: string;
  navActiveBg: string;
  navInactiveText: string;
  toggleBg: string;
  toggleFg: string;
};

export const LIGHT: Theme = {
  bg: '#f5f7ff',
  card: '#ffffff',
  cardHead: '#eef1fb',
  border: '#d0d8f0',
  primary: '#3b6bef',
  primaryHover: '#2a56d4',
  text: '#111827',
  muted: '#6b7280',
  dimmer: '#9ca3af',
  label: '#374151',
  inputBg: '#ffffff',
  lockedBg: '#eef1fb',
  lockedText: '#6b7280',
  success: '#16a34a',
  warn: '#d97706',
  error: '#dc2626',
  successBg: '#f0fdf4',
  successBorder: '#86efac',
  errorBg: '#fef2f2',
  errorBorder: '#fca5a5',
  withoutAccent: '#dc2626',
  withAccent: '#2563eb',
  barBg: '#dbeafe',
  latencyColor: '#7c3aed',
  tableRowBorder: '#e5e9f8',
  toastBg: '#ffffff',
  navBg: '#ffffff',
  navBorder: '#d0d8f0',
  navText: '#111827',
  navActiveText: '#3b6bef',
  navActiveBg: '#eef1fb',
  navInactiveText: '#6b7280',
  toggleBg: '#eef1fb',
  toggleFg: '#3b6bef',
};

export const DARK: Theme = {
  bg: '#0d1117',
  card: '#161c27',
  cardHead: '#1c2333',
  border: '#2a3650',
  primary: '#4d80f0',
  primaryHover: '#3b6bef',
  text: '#e2e8f0',
  muted: '#8b9ab2',
  dimmer: '#6b7a94',
  label: '#a8b8d0',
  inputBg: '#1c2333',
  lockedBg: '#151b28',
  lockedText: '#6b7a94',
  success: '#22c55e',
  warn: '#fbbf24',
  error: '#f87171',
  successBg: '#052e16',
  successBorder: '#166534',
  errorBg: '#2d0a0a',
  errorBorder: '#7f1d1d',
  withoutAccent: '#f87171',
  withAccent: '#60a5fa',
  barBg: '#1e3a5f',
  latencyColor: '#a78bfa',
  tableRowBorder: '#1e293b',
  toastBg: '#1c2333',
  navBg: '#0d1117',
  navBorder: '#2a3650',
  navText: '#e2e8f0',
  navActiveText: '#60a5fa',
  navActiveBg: '#1e2d45',
  navInactiveText: '#8b9ab2',
  toggleBg: '#1c2333',
  toggleFg: '#60a5fa',
};
